import type { ChatMessage } from './chat';
import type { ChatRoomItem } from '@/components/chat/ChatList';

// ============================================================
// Helper: create a date string for N days ago at given hour:minute
// ============================================================
function daysAgo(days: number, hour: number, minute: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function today(hour: number, minute: number): string {
  return daysAgo(0, hour, minute);
}

function yesterday(hour: number, minute: number): string {
  return daysAgo(1, hour, minute);
}

// ============================================================
// CUSTOMER chat rooms & messages
// ============================================================

export const customerChatRooms: ChatRoomItem[] = [
  {
    id: 'cust-chat-001',
    name: '박정훈 기사님',
    avatar: '박',
    avatarColor: 'bg-blue-100 text-blue-600',
    lastMessage: '네, 출발 시간 확인했습니다. 10분 전에 도착하겠습니다.',
    time: '오후 3:42',
    unreadCount: 2,
    isOnline: true,
    subtitle: '서울 → 속초 | 45인승 | 4월 15일',
  },
  {
    id: 'cust-chat-002',
    name: '최영호 기사님',
    avatar: '최',
    avatarColor: 'bg-purple-100 text-purple-600',
    lastMessage: '견적서 보내드렸습니다. 확인 부탁드립니다.',
    time: '어제',
    unreadCount: 1,
    isOnline: false,
    subtitle: '서울 → 강릉 | 28인승 | 4월 22일',
  },
  {
    id: 'cust-chat-003',
    name: '김태호 기사님',
    avatar: '김',
    avatarColor: 'bg-green-100 text-green-600',
    lastMessage: '안전 운행하겠습니다. 감사합니다!',
    time: '3일 전',
    unreadCount: 0,
    isOnline: false,
    subtitle: '서울 → 부산 | 45인승 | 3월 10일',
  },
  {
    id: 'cust-chat-004',
    name: '이상민 기사님',
    avatar: '이',
    avatarColor: 'bg-amber-100 text-amber-600',
    lastMessage: '결제 확인되었습니다. 당일 뵙겠습니다!',
    time: '1주 전',
    unreadCount: 0,
    isOnline: true,
    subtitle: '인천 → 전주 | 33인승 | 5월 3일',
  },
  {
    id: 'cust-chat-005',
    name: '정우진 기사님',
    avatar: '정',
    avatarColor: 'bg-red-100 text-red-600',
    lastMessage: '네, 수하물 적재 공간 충분합니다.',
    time: '2주 전',
    unreadCount: 0,
    isOnline: false,
    subtitle: '서울 → 경주 | 45인승 | 2월 28일',
  },
];

export const customerChatMessages: ChatMessage[] = [
  // 2 days ago
  {
    id: 'cm-001',
    roomId: 'cust-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '견적 요청이 접수되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: daysAgo(2, 9, 0),
  },
  {
    id: 'cm-002',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '안녕하세요, 박정훈 기사입니다. 4월 15일 속초 여행 건 견적 요청 확인했습니다.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 9, 5),
  },
  {
    id: 'cm-003',
    roomId: 'cust-chat-001',
    senderId: 'customer-001',
    senderName: '나',
    content: '안녕하세요! 서울 강남역 출발이고, 인원은 35명입니다. 왕복으로 부탁드려요.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 9, 8),
  },
  {
    id: 'cm-004',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '네, 45인승 대형버스로 준비하겠습니다. 출발 시간은 몇 시를 원하시나요?',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 9, 12),
  },
  {
    id: 'cm-005',
    roomId: 'cust-chat-001',
    senderId: 'customer-001',
    senderName: '나',
    content: '오전 8시 출발이면 좋겠습니다. 돌아오는 건 오후 6시쯤 출발하면 될까요?',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 9, 15),
  },
  {
    id: 'cm-006',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '네, 가능합니다. 견적서 준비해서 보내드리겠습니다. 잠시만 기다려주세요.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 9, 18),
  },
  // Yesterday
  {
    id: 'cm-007',
    roomId: 'cust-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '견적서가 전송되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: yesterday(10, 0),
  },
  {
    id: 'cm-008',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '견적서 보내드렸습니다. 왕복 기준 85만원이며, 고속도로 통행료 포함입니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(10, 2),
  },
  {
    id: 'cm-009',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '견적서_속초여행_0415.pdf',
    type: 'file',
    fileName: '견적서_속초여행_0415.pdf',
    isRead: true,
    createdAt: yesterday(10, 3),
  },
  {
    id: 'cm-010',
    roomId: 'cust-chat-001',
    senderId: 'customer-001',
    senderName: '나',
    content: '견적서 확인했습니다. 가격 괜찮네요! 진행하겠습니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(11, 30),
  },
  {
    id: 'cm-011',
    roomId: 'cust-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '견적이 수락되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: yesterday(11, 31),
  },
  {
    id: 'cm-012',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '감사합니다! 결제 진행해주시면 예약 확정됩니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(11, 35),
  },
  {
    id: 'cm-013',
    roomId: 'cust-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '결제가 완료되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: yesterday(14, 0),
  },
  // Today
  {
    id: 'cm-014',
    roomId: 'cust-chat-001',
    senderId: 'customer-001',
    senderName: '나',
    content: '안녕하세요, 기사님! 출발 장소를 강남역 10번 출구 앞으로 해도 될까요?',
    type: 'text',
    isRead: true,
    createdAt: today(14, 30),
  },
  {
    id: 'cm-015',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '네, 강남역 10번 출구 앞이면 대형버스 정차 가능합니다.',
    type: 'text',
    isRead: true,
    createdAt: today(14, 35),
  },
  {
    id: 'cm-016',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '현재 위치를 공유했습니다.',
    type: 'location',
    locationLabel: '강남역 10번 출구',
    latitude: 37.498095,
    longitude: 127.027610,
    isRead: true,
    createdAt: today(14, 36),
  },
  {
    id: 'cm-017',
    roomId: 'cust-chat-001',
    senderId: 'customer-001',
    senderName: '나',
    content: '완벽합니다! 혹시 당일에 짐이 많은데, 하부 트렁크 사용 가능한가요?',
    type: 'text',
    isRead: true,
    createdAt: today(15, 0),
  },
  {
    id: 'cm-018',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '물론이죠! 45인승 대형버스라 하부 트렁크 넉넉합니다. 캐리어 35개도 충분히 실을 수 있어요.',
    type: 'text',
    isRead: false,
    createdAt: today(15, 40),
  },
  {
    id: 'cm-019',
    roomId: 'cust-chat-001',
    senderId: 'driver-001',
    senderName: '박정훈 기사님',
    content: '네, 출발 시간 확인했습니다. 10분 전에 도착하겠습니다.',
    type: 'text',
    isRead: false,
    createdAt: today(15, 42),
  },
];

// ============================================================
// DRIVER chat rooms & messages
// ============================================================

export const driverChatRooms: ChatRoomItem[] = [
  {
    id: 'drv-chat-001',
    name: '김민수 고객님',
    avatar: '김',
    avatarColor: 'bg-blue-100 text-blue-600',
    lastMessage: '출발 장소를 강남역 10번 출구 앞으로 변경 가능할까요?',
    time: '오후 2:30',
    unreadCount: 1,
    isOnline: true,
    subtitle: '서울 → 속초 | 35명 | 3월 20일',
  },
  {
    id: 'drv-chat-002',
    name: '이수진 고객님',
    avatar: '이',
    avatarColor: 'bg-pink-100 text-pink-600',
    lastMessage: '감사합니다! 내일 뵙겠습니다.',
    time: '오전 11:15',
    unreadCount: 0,
    isOnline: false,
    subtitle: '서울 → 강릉 | 20명 | 3월 18일',
  },
  {
    id: 'drv-chat-003',
    name: '박서연 고객님',
    avatar: '박',
    avatarColor: 'bg-purple-100 text-purple-600',
    lastMessage: '견적서 확인했습니다. 진행하겠습니다!',
    time: '어제',
    unreadCount: 0,
    isOnline: true,
    subtitle: '인천 → 전주 | 42명 | 4월 5일',
  },
  {
    id: 'drv-chat-004',
    name: '최영호 고객님',
    avatar: '최',
    avatarColor: 'bg-green-100 text-green-600',
    lastMessage: '워크숍 일정이 변경되어서 연락드렸습니다.',
    time: '3일 전',
    unreadCount: 3,
    isOnline: false,
    subtitle: '서울 → 양평 | 28명 | 4월 10일',
  },
  {
    id: 'drv-chat-005',
    name: '정하나 고객님',
    avatar: '정',
    avatarColor: 'bg-amber-100 text-amber-600',
    lastMessage: '수고하셨습니다. 좋은 하루 되세요!',
    time: '1주 전',
    unreadCount: 0,
    isOnline: false,
    subtitle: '서울 → 경주 | 45명 | 3월 5일',
  },
];

export const driverChatMessages: ChatMessage[] = [
  // Yesterday
  {
    id: 'dm-001',
    roomId: 'drv-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '새로운 견적 요청이 접수되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: daysAgo(2, 10, 0),
  },
  {
    id: 'dm-002',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '안녕하세요, 3월 20일 강원도 속초 운행 관련하여 문의드립니다.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 5),
  },
  {
    id: 'dm-003',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '안녕하세요! 김민수 고객님, 견적 요청 확인했습니다. 어떤 부분이 궁금하신가요?',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 8),
  },
  {
    id: 'dm-004',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '출발 시간을 8시에서 7시 30분으로 변경할 수 있을까요? 인원이 35명이라 일찍 출발하면 좋을 것 같아서요.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 12),
  },
  {
    id: 'dm-005',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '네, 7시 30분 출발도 가능합니다. 변경해드리겠습니다.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 15),
  },
  {
    id: 'dm-006',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '감사합니다! 중간에 휴게소 한 번 들러주실 수 있나요?',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 18),
  },
  {
    id: 'dm-007',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '물론이죠. 용인 휴게소에서 15분 정도 정차할 예정입니다. 고속도로 상황에 따라 횡성 휴게소로 변경될 수 있습니다.',
    type: 'text',
    isRead: true,
    createdAt: daysAgo(2, 10, 22),
  },
  {
    id: 'dm-008',
    roomId: 'drv-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '운행 일시가 변경되었습니다: 2026-03-20 07:30',
    type: 'system',
    isRead: true,
    createdAt: daysAgo(2, 10, 25),
  },
  // Yesterday
  {
    id: 'dm-009',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '견적서 준비되었습니다. 왕복 기준 80만원입니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(9, 0),
  },
  {
    id: 'dm-010',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '견적서_김민수_속초_0320.pdf',
    type: 'file',
    fileName: '견적서_김민수_속초_0320.pdf',
    isRead: true,
    createdAt: yesterday(9, 1),
  },
  {
    id: 'dm-011',
    roomId: 'drv-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '견적이 수락되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: yesterday(11, 0),
  },
  {
    id: 'dm-012',
    roomId: 'drv-chat-001',
    senderId: 'system',
    senderName: '시스템',
    content: '결제가 완료되었습니다.',
    type: 'system',
    isRead: true,
    createdAt: yesterday(14, 0),
  },
  {
    id: 'dm-013',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '결제 완료했습니다! 당일 잘 부탁드립니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(14, 5),
  },
  {
    id: 'dm-014',
    roomId: 'drv-chat-001',
    senderId: 'driver-001',
    senderName: '나',
    content: '네, 안전 운행하겠습니다. 당일 출발 10분 전에 도착하여 대기하겠습니다.',
    type: 'text',
    isRead: true,
    createdAt: yesterday(14, 10),
  },
  // Today
  {
    id: 'dm-015',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '기사님, 한 가지 더 문의드립니다.',
    type: 'text',
    isRead: true,
    createdAt: today(14, 25),
  },
  {
    id: 'dm-016',
    roomId: 'drv-chat-001',
    senderId: 'customer-001',
    senderName: '김민수',
    content: '출발 장소를 강남역 10번 출구 앞으로 변경 가능할까요?',
    type: 'text',
    isRead: false,
    createdAt: today(14, 30),
  },
];

// ============================================================
// PENSION chat rooms & messages
// ============================================================

export const pensionChatRooms: ChatRoomItem[] = [
  {
    id: 'pen-chat-001',
    name: '박서연 고객님',
    avatar: '박',
    avatarColor: 'bg-pink-100 text-pink-600',
    lastMessage: '체크인 시간 변경 가능한가요? 좀 일찍 도착할 것 같아서요.',
    time: '오후 1:30',
    unreadCount: 1,
    isOnline: true,
    subtitle: '워크숍 패키지 | 4월 5~6일 | 42명',
  },
  {
    id: 'pen-chat-002',
    name: '김민수 고객님',
    avatar: '김',
    avatarColor: 'bg-blue-100 text-blue-600',
    lastMessage: '감사합니다! 즐거운 여행이었어요.',
    time: '어제',
    unreadCount: 0,
    isOnline: false,
    subtitle: '가족 여행 패키지 | 3월 15~16일 | 15명',
  },
  {
    id: 'pen-chat-003',
    name: '최영호 고객님',
    avatar: '최',
    avatarColor: 'bg-green-100 text-green-600',
    lastMessage: '바비큐 그릴 대여도 가능한가요?',
    time: '3일 전',
    unreadCount: 2,
    isOnline: false,
    subtitle: 'MT 패키지 | 4월 20~21일 | 30명',
  },
];
